<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOfhSlEv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOfhSlEv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOfhSlEv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOfhSlEv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOfhSlEv\App_KernelDevDebugContainer([
    'container.build_hash' => 'OfhSlEv',
    'container.build_id' => 'e2eec467',
    'container.build_time' => 1696869584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOfhSlEv');
