<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_booking_create' => [[], ['_controller' => 'App\\Controller\\ApiController::createBooking'], [], [['text', '/api/booking/create']], [], [], []],
    'api_bookings_get' => [[], ['_controller' => 'App\\Controller\\ApiController::getBookings'], [], [['text', '/api/bookings']], [], [], []],
    'api_booking_update' => [['id'], ['_controller' => 'App\\Controller\\ApiController::updateBooking'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/booking']], [], [], []],
    'api_booking_delete' => [['id'], ['_controller' => 'App\\Controller\\ApiController::deleteBooking'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/booking/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
